export const data = [
  {
    role: 'dev Frontend',
    fullname: 'Bui Dinh Loc',
    avatar: process.env.PUBLIC_URL + '/images/avatar.jpg',
    dateOfBirth: '06/03/2001',
    address: 'HMC city, Viet Nam',
    phone: '0969819201',
    mail: 'dinhloc334@gmail.com',
    githubLink: '#',
    facebookLink: 'https://www.facebook.com/dinhlocpisces/',
    intagramLink: '#',
    twitterLink: '#',
    youtubeLink: '#',
  },
  {
    role: 'dev Backend',
    fullname: 'Nguyen Phung Le Luan',
    avatar: process.env.PUBLIC_URL + '/images/luanImg.jpg',
    dateOfBirth: '01/07/2001',
    address: 'HMC city, Viet Nam',
    phone: '0966053416',
    mail: 'leenguyen1721@gmail.com',
    githubLink: '#',
    facebookLink: '#',
    intagramLink: '#',
    twitterLink: '#',
    youtubeLink: '#',
  },
  {
    role: 'dev Frontend',
    fullname: 'Diep The Vuong Huy',
    avatar: process.env.PUBLIC_URL + '/images/huyImg.webp',
    dateOfBirth: '17/07/2001',
    address: 'HMC city, Viet Nam',
    phone: '0368884816',
    mail: 'vuonghuy1772001@gmail.com',
    githubLink: 'https://github.com/VuongHuy2k1',
    facebookLink: 'https://www.facebook.com/huy.diep.3388630/',
    intagramLink: '#',
    twitterLink: '#',
    youtubeLink: '#',
  },
  {
    role: 'dev Frontend',
    fullname: 'Huynh Nguyen Thach',
    avatar: process.env.PUBLIC_URL + '/images/thachImg.jpg',
    dateOfBirth: '18/09/2001',
    address: 'HMC city, Viet Nam',
    phone: '0984141206',
    mail: 'thachhuynhit.ut@gmail.com',
    githubLink: '#',
    facebookLink: '#',
    intagramLink: '#',
    twitterLink: '#',
    youtubeLink: '#',
  },
];
